// video
export const videoCardData = [
  {
    id: 0,
    img_poster: "/assets/m_1.png",
    userImg: "/assets/m_u1.png",
    title1: "A paragraph is a series of sentences that are Alam123",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 1,
    img_poster: "/assets/m1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 2,
    img_poster: "/assets/m3.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 3,
    img_poster: "/assets/m1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 4,
    img_poster: "/assets/m2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 5,
    img_poster: "/assets/m1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 6,
    img_poster: "/assets/m3.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 7,
    img_poster: "/assets/m1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
];
// short
export const shortVideoData = [
  {
    id: 0,
    img_poster: "/assets/s1.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 1,
    img_poster: "/assets/s2.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 2,
    img_poster: "/assets/s3.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 3,
    img_poster: "/assets/s4.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 3,
    img_poster: "/assets/s5.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 3,
    img_poster: "/assets/s4.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 3,
    img_poster: "/assets/s3.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 3,
    img_poster: "/assets/s2.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 3,
    img_poster: "/assets/s1.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 3,
    img_poster: "/assets/s5.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
];
// breaking news
export const brekingNewsdData = [
  {
    id: 0,
    img_poster: "/assets/b1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 1,
    img_poster: "/assets/b2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 2,
    img_poster: "/assets/b1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 3,
    img_poster: "/assets/b2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 4,
    img_poster: "/assets/b1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 5,
    img_poster: "/assets/b2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 6,
    img_poster: "/assets/b1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 7,
    img_poster: "/assets/b2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
];
// breaking news
export const infinityData = [
  {
    id: 0,
    img_poster: "/assets/i1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 1,
    img_poster: "/assets/i2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 2,
    img_poster: "/assets/i3.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 3,
    img_poster: "/assets/i4.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 4,
    img_poster: "/assets/i5.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 5,
    img_poster: "/assets/i6.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 6,
    img_poster: "/assets/i5.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 7,
    img_poster: "/assets/i4.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 7,
    img_poster: "/assets/i3.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 7,
    img_poster: "/assets/i2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 7,
    img_poster: "/assets/i6.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
];
