// scrollable button
export const scrollablebtn = [
  { id: 0, title: "All" },
  { id: 0, title: "Mixes" },
  { id: 0, title: "React.Js" },
  { id: 0, title: "Mern" },
  { id: 0, title: "Music" },
  { id: 0, title: "BPraak" },
  { id: 0, title: "Bollywood" },
  { id: 0, title: "Adhan" },
  { id: 0, title: "Tranding" },
  { id: 0, title: "Live" },
  { id: 0, title: "Song" },
  { id: 0, title: "Comedy" },
  { id: 0, title: "Javascript" },
  { id: 0, title: "Electroni" },
  { id: 0, title: "Watched" },
  { id: 0, title: "Not" },
  { id: 0, title: "Recently" },
  { id: 0, title: "Case" },
  { id: 0, title: "Study" },
  { id: 0, title: "Cook" },
  { id: 0, title: "Studio" },
  { id: 0, title: "Lofi" },
  { id: 0, title: "Tour" },
  { id: 0, title: "Saintmartin" },
  { id: 0, title: "Tech" },
  { id: 0, title: "iPhone" },
  { id: 0, title: "UI" },
  { id: 0, title: "UX" },
  { id: 0, title: "Computer" },
];
// video
export const videoCardData = [
  {
    id: 0,
    img_poster: "/assets/m_1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 1,
    img_poster: "/assets/m1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 2,
    img_poster: "/assets/m3.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 3,
    img_poster: "/assets/m1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 4,
    img_poster: "/assets/m2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 5,
    img_poster: "/assets/m1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 6,
    img_poster: "/assets/m3.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 7,
    img_poster: "/assets/m1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
];
// short
export const shortVideoData = [
  {
    id: 0,
    img_poster: "/assets/s1.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 1,
    img_poster: "/assets/s2.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 2,
    img_poster: "/assets/s3.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 3,
    img_poster: "/assets/s4.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 3,
    img_poster: "/assets/s5.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 3,
    img_poster: "/assets/s4.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 3,
    img_poster: "/assets/s3.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 3,
    img_poster: "/assets/s2.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 3,
    img_poster: "/assets/s1.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 3,
    img_poster: "/assets/s5.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
];
// breaking news
export const brekingNewsdData = [
  {
    id: 0,
    img_poster: "/assets/b1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 1,
    img_poster: "/assets/b2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 2,
    img_poster: "/assets/b1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 3,
    img_poster: "/assets/b2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 4,
    img_poster: "/assets/b1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 5,
    img_poster: "/assets/b2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 6,
    img_poster: "/assets/b1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 7,
    img_poster: "/assets/b2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
];
// breaking news
export const infinityData = [
  {
    id: 0,
    img_poster: "/assets/i1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 1,
    img_poster: "/assets/i2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 2,
    img_poster: "/assets/i3.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 3,
    img_poster: "/assets/i4.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 4,
    img_poster: "/assets/i5.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 5,
    img_poster: "/assets/i6.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 6,
    img_poster: "/assets/i5.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 7,
    img_poster: "/assets/i4.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 7,
    img_poster: "/assets/i3.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 7,
    img_poster: "/assets/i2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 7,
    img_poster: "/assets/i6.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
];
